apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-express-app
  labels:
    app: basic-express-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: basic-express-app
  template:
    metadata:
      labels:
        app: basic-express-app
    spec:
      containers:
      - name: basic-express-app
        image: angadnagar/jenkins-cicd:replaceImageTag
        ports:
        - containerPort: 3000
